import Rating from '@mui/material/Rating';


const productsData = [
    {
        id: 1,
        image: "./assets/images/jbl-blue.png",
        name: "JBL T450",
        desc: 'The best noise cancelling with two high performance procesors and eight microphones.',
        rating: "5.0",
        stars: <Rating name="read-only" value={5} readOnly />,
        reviews: 274,
        price:  298,
        amount: 1,
    },
    {
        id: 2,
        image: "./assets/images/jbl-black-2.png",
        name: "JBL C45BT",
        desc: 'The best noise cancelling with two high performance procesors and eight microphones.',
        rating: '4.0',
        stars: <Rating name="read-only" value={4} readOnly />,
        reviews: 274,
        price:  298,
        amount: 1,
    },
    {
        id: 3,
        image: "./assets/images/jbl-3.png",
        name: "JBL T450",
        desc: 'The best noise cancelling with two high performance procesors and eight microphones.',
        rating: "4.0",
        stars: <Rating name="read-only" value={4} readOnly />,
        reviews: 274,
        price:  298,
        amount: 1,
    },
    {
        id: 4,
        image: "./assets/images/jbl-4.png",
        name: "JBL Soundcore",
        desc: 'The best noise cancelling with two high performance procesors and eight microphones.',
        rating: "5.0",
        stars: <Rating name="read-only" value={5} readOnly />,
        reviews: 274,
        price:  298,
        amount: 1,
    },
    {
        id: 5,
        image: "./assets/images/sony-8.png",
        name: "SONY CH320",
        desc: 'The best noise cancelling with two high performance procesors and eight microphones.',
        rating: "3.0",
        stars: <Rating name="read-only" value={3} readOnly />,
        reviews: 274,
        price:  298,
        amount: 1,
    },
    {
        id: 6,
        image: "./assets/images/jbl-5.png",
        name: "JBL T640",
        desc: 'The best noise cancelling with two high performance procesors and eight microphones.',
        rating: "5.0",
        stars: <Rating name="read-only" value={5} readOnly />,
        reviews: 274,
        price:  298,
        amount: 1,
    },
    {
        id: 7,
        image: "./assets/images/img-6.png",
        name: "JBL T450",
        desc: 'The best noise cancelling with two high performance procesors and eight microphones.',
        rating: "5.0",
        stars: <Rating name="read-only" value={5} readOnly />,
        reviews: 274,
        price:  298,
        amount: 1,
    },
    {
        id: 8,
        image: "./assets/images/marshal-1.png",
        name: "MARSHAL IV",
        desc: 'The best noise cancelling with two high performance procesors and eight microphones.',
        rating: "5.0",
        stars: <Rating name="read-only" value={4} readOnly />,
        reviews: 274,
        price:  298,
        amount: 1,
    },
    {
        id: 9,
        image: "./assets/images/p-1.png",
        name: "PHILIPS BOLD BASS",
        desc: 'The best noise cancelling with two high performance procesors and eight microphones.',
        rating: "3.0",
        stars: <Rating name="read-only" value={5} readOnly />,
        reviews: 274,
        price:  298,
        amount: 1,
    },
    {
        id: 10,
        image: "./assets/images/jbl-6.png",
        name: "JBL T760 NC",
        desc: 'The best noise cancelling with two high performance procesors and eight microphones.',
        rating: "3.5",
        stars: <Rating name="read-only" value={3} readOnly />,
        reviews: 274,
        price:  298,
        amount: 1,
    },
    {
        id: 11,
        image: "./assets/images/sony-5.png",
        name: "SONY CH201",
        desc: 'The best noise cancelling with two high performance procesors and eight microphones.',
        rating: "5.0",
        stars: <Rating name="read-only" value={5} readOnly />,
        reviews: 274,
        price:  298,
        amount: 1,
    },
    {
        id: 12,
        image: "./assets/images/sony-7.png",
        name: "SONY CH912",
        desc: 'The best noise cancelling with two high performance procesors and eight microphones.',
        rating: "5.0",
        stars: <Rating name="read-only" value={5} readOnly />,
        reviews: 274,
        price:  298,
        amount: 1,
    },
]

export default productsData;
